### ISSUE TITLE
error: No suitable connection found

### ISSUE THREAD

**Issue by dataedgehungary** [SergeiSemenkov/eMondrian#5]
Need some help with a fresh install:

```
ERROR mondrian.xmla.XmlaServlet - Errors when handling XML/A message
Mar 01 11:06:52 de_support1.localdomain server[20452]: mondrian.xmla.XmlaException: Mondrian Error:XMLA Discover unparse results error
Mar 01 11:06:52 de_support1.localdomain server[20452]: at mondrian.xmla.XmlaHandler.discover(XmlaHandler.java:3505) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at mondrian.xmla.XmlaHandler.process(XmlaHandler.java:702) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at mondrian.xmla.impl.DefaultXmlaServlet.handleSoapBody(DefaultXmlaServlet.java:520) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at mondrian.xmla.XmlaServlet.doPost(XmlaServlet.java:320) [mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at javax.servlet.http.HttpServlet.service(HttpServlet.java:650) [tomcat-servlet-3.0-api.jar:?]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) [tomcat-servlet-3.0-api.jar:?]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.76]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.76]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat7-websocket.jar:7.0.76]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.76]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.76]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218) [catalina.jar:7.0.76]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110) [catalina.jar:7.0.76]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:498) [catalina.jar:7.0.76]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) [catalina.jar:7.0.76]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.76]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962) [catalina.jar:7.0.76]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.76]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445) [catalina.jar:7.0.76]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-coyote.jar:7.0.76]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637) [tomcat-coyote.jar:7.0.76]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316) [tomcat-coyote.jar:7.0.76]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_322]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_322]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.76]
Mar 01 11:06:52 de_support1.localdomain server[20452]: at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
Mar 01 11:06:52 de_support1.localdomain server[20452]: Caused by: mondrian.olap.MondrianException: Mondrian Error:Internal error: No suitable connection found
```

**Comment by dataedgehungary** [comment]
all good with Tomcat 9.0
