### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alexoff13** [SergeiSemenkov/eMondrian#8]
I get The Mondrian XML: Timeout waiting for idle object when expanding hierarchy in excel. How can I fix this?

**Comment by alexoff13** [comment]
OLAP cube is connected to ClickHouse

**Comment by SergeiSemenkov** [comment]
Start from checking mondran sql log. If it is timeout error from ClickHouse change timeout setting for your ClickHouse connection.

**Comment by alexoff13** [comment]
We looked at the logs, there is nothing strange there, except for these last lines
![telegram-cloud-photo-size-2-5231007383705208227-x](https://user-images.githubusercontent.com/63997514/206667748-a78f1c07-010d-4ab6-9d41-b2be034fa3e6.jpg)

**Comment by alexoff13** [comment]
Also getting the following error: The Mondrian XML: Connection reset. At the same time, there is practically no load on the database server

**Comment by SergeiSemenkov** [comment]
Mondrian XML error messages must be in mondrian.log. Could you find and place them here?

**Comment by alexoff13** [comment]
Last error in this file:
```
group by
    `olap_mart_sales_stocks`.`departament`,
    `olap_mart_sales_stocks`.`category_name1`,
    `olap_mart_sales_stocks`.`category_name2`,
    `olap_mart_sales_stocks`.`category_name3`]
	at mondrian.resource.MondrianResource$_Def0.ex(MondrianResource.java:1002) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.olap.Util.newInternal(Util.java:2490) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.olap.Util.newError(Util.java:2506) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.SqlStatement.handle(SqlStatement.java:366) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.SqlStatement.execute(SqlStatement.java:260) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.RolapUtil.executeQuery(RolapUtil.java:352) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.agg.SegmentLoader.createExecuteSql(SegmentLoader.java:484) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.agg.SegmentLoader.loadImpl(SegmentLoader.java:162) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.agg.SegmentLoader.access$000(SegmentLoader.java:53) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.agg.SegmentLoader$SegmentLoadCommand.call(SegmentLoader.java:143) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.agg.SegmentLoader$SegmentLoadCommand.call(SegmentLoader.java:122) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot get a connection, pool exhausted
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:103) ~[commons-dbcp-1.2.1.jar:1.2.1]
	at mondrian.rolap.SqlStatement.execute(SqlStatement.java:146) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.RolapUtil.executeQuery(RolapUtil.java:352) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.agg.SegmentLoader.createExecuteSql(SegmentLoader.java:484) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.agg.SegmentLoader.loadImpl(SegmentLoader.java:162) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.agg.SegmentLoader.access$000(SegmentLoader.java:53) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.agg.SegmentLoader$SegmentLoadCommand.call(SegmentLoader.java:143) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.agg.SegmentLoader$SegmentLoadCommand.call(SegmentLoader.java:122) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
Caused by: java.util.NoSuchElementException: Timeout waiting for idle object
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:756) ~[commons-pool-1.2.jar:1.2]
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:95) ~[commons-dbcp-1.2.1.jar:1.2.1]
	at mondrian.rolap.SqlStatement.execute(SqlStatement.java:146) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.RolapUtil.executeQuery(RolapUtil.java:352) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.agg.SegmentLoader.createExecuteSql(SegmentLoader.java:484) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.agg.SegmentLoader.loadImpl(SegmentLoader.java:162) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.agg.SegmentLoader.access$000(SegmentLoader.java:53) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.agg.SegmentLoader$SegmentLoadCommand.call(SegmentLoader.java:143) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at mondrian.rolap.agg.SegmentLoader$SegmentLoadCommand.call(SegmentLoader.java:122) ~[mondrian-9.3.0.0-SNAPSHOT.jar:9.3.0.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
```

**Comment by alexoff13** [comment]
> 
Start of error message:
```
Caused by: mondrian.olap.MondrianException: Mondrian Error:Internal error: Error while loading segment; sql=[select
```

**Comment by SergeiSemenkov** [comment]
Obviously something wrong with dbcp connection pool.
Try to play with socket_timeout setting for your ClickHouse connection first.

**Comment by alexoff13** [comment]
We initially increased this parameter, but it still doesn't help: 
```
<DataSources>
  <DataSource>
    <DataSourceName>mart_comm</DataSourceName>
    <DataSourceDescription>fact_sales_all</DataSourceDescription>
    <URL>http://localhost:8080/mondrian/xmla</URL>
    <DataSourceInfo>Provider=mondrian; Jdbc=jdbc:clickhouse://<host>:8123/<name_db>?socket_timeout=300000; JdbcTimeout=600; JdbcDrivers=ru.yandex.clickhouse.ClickHouseDriver; JdbcUser=<login>; JdbcPassword=<password></DataSourceInfo>
    <ProviderName>Mondrian</ProviderName>
    <ProviderType>MDP</ProviderType>
    <AuthenticationMode>Unauthenticated</AuthenticationMode>
    <Catalogs>
        <Catalog name="mart_comm">
            <Definition>/WEB-INF/schema/mart_com.xml</Definition>
        </Catalog>
    </Catalogs>
  </DataSource>
</DataSources>
```

**Comment by SergeiSemenkov** [comment]
Let's arrange a meeting. It will be easier. Write me please at siarhei.semiankou@gmail.com

**Comment by alexoff13** [comment]
The error was solved by increasing the pool of connections to the database. This is done using the parameters `jdbc.maxIdle` and `jdbc.maxTotal` in `WEB-INF/datasources.xml`. 

Learn more about these options: 
https://sergeisemenkov.github.io/eMondrian/original_docs/configuration.html#Connect_string_properties
https://commons.apache.org/proper/commons-dbcp/configuration.html

My connection to ClickHouse:
```xml
        <DataSourceInfo>Provider=mondrian;
            Jdbc=jdbc:clickhouse://<host>:8123/<db>?socket_timeout=300000; JdbcTimeout=600;
            JdbcDrivers=ru.yandex.clickhouse.ClickHouseDriver; JdbcUser=<user>; JdbcPassword=<pass>;
            jdbc.maxIdle=20;
            jdbc.maxTotal=20
        </DataSourceInfo>
```

Thanks to @SergeiSemenkov  for help :)
